### ISSUE TITLE
模板有错

### ISSUE THREAD

**Issue by onesbyones** [7sDream/django-intro-zh#15]
# 第一个 Django 项目 - 第三部分
## 去除模板中的硬编码 URL

模板中的标签使用方法不对，如下：

原文：`<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>`

这样会抛异常

需要修改成：`<li><a href="{% url 'detail' %} {{question.id}}">{{ question.question_text }}</a></li>`

**Comment by 7sDream** [comment]
你确定么？

我看 Django 的官方文档也是这么写的。

而且 Django Template 的 built-in tag url 的文档也是这么示例的：

参见：https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#url

所以应该不是文档问题吧，你再和文档里的对比一下试试。

**Comment by heqinghai** [comment]
^_^我也是刚学Django，用的是1.8.16

视图方法：

‘’’
def index_for_url(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    print latest_question_list
    context = {'latest_question_list': latest_question_list, 'title': 'index_for_url'}    
    return render(request, 'polls/index_for_url.html', context)
‘’’

URL配置：

'''
        url(r'^index_for_url/$', views.index_for_url, name='index_for_url'),
        url(r'^index_for_url/(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
'''

**Comment by onesbyones** [comment]
按照文档来确实出现了这个问题，但是我把修改后就不会导致模板异常了。配置如下：

<div style="font-family: 'Lucida Grande', 'Segoe UI', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Lucida Sans Unicode', Helvetica, Arial, sans-serif; font-size: 0.9em; overflow-x: hidden; overflow-y: auto; margin: 0px !important; padding: 5px 20px 26px !important; background-color: rgb(255, 255, 255);font-family: 'Hiragino Sans GB', 'Microsoft YaHei', STHeiti, SimSun, 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', 'Segoe UI', AppleSDGothicNeo-Medium, 'Malgun Gothic', Verdana, Tahoma, sans-serif; padding: 20px;padding: 20px; color: rgb(34, 34, 34); font-size: 15px; font-family: 'Roboto Condensed', Tauri, 'Hiragino Sans GB', 'Microsoft YaHei', STHeiti, SimSun, 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', 'Segoe UI', AppleSDGothicNeo-Medium, 'Malgun Gothic', Verdana, Tahoma, sans-serif; line-height: 1.6; -webkit-font-smoothing: antialiased; background: rgb(255, 255, 255);"><p style="margin: 1em 0px; word-wrap: break-word;"><strong>模板文件</strong></p><hr style="stroke: none; opacity: 0.2;stroke: none; opacity: 0.2;border: 1px solid rgb(204, 204, 204);border: 1px solid rgb(230, 230, 230);"><p style="margin: 1em 0px; word-wrap: break-word;">这样会触发模板异常</p><pre style="border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); overflow: auto; padding: 0.5em;"><code data-origin="<pre><code>
&amp;lt;html&amp;gt;
&amp;lt;head&amp;gt;
    &amp;lt;title&amp;gt;{{title}}&amp;lt;/title&amp;gt;
&amp;lt;/head&amp;gt;
&amp;lt;body&amp;gt;
    &amp;lt;h1&amp;gt;hello index_for_url demo&amp;lt;/h1&amp;gt;
    {% if latest_question_list %}
        &amp;lt;ul&amp;gt;
            {% for question in latest_question_list%}
                &amp;lt;li&amp;gt;&amp;lt;a href=&quot;{% url 'polls:index_for_url' question.id %}&quot;&amp;gt;{{question.question_text}}&amp;lt;/a&amp;gt;&amp;lt;/li&amp;gt;
            {% endfor %}
        &amp;lt;/ul&amp;gt;
    {% else %}
        &amp;lt;p&amp;gt;No polls are availabel.&amp;lt;/p&amp;gt;
    {% endif %}
&amp;lt;/body&amp;gt;
&amp;lt;/html&amp;gt;
</code></pre>" style="border: 0px; display: block;font-family: Consolas, Inconsolata, Courier, monospace; font-weight: bold; white-space: pre; margin: 0px;border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); padding: 0px 5px; margin: 0px 2px;font-size: 1em; letter-spacing: -1px; font-weight: bold;">
&lt;html&gt;
&lt;head&gt;
    &lt;title&gt;{{title}}&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    &lt;h1&gt;hello index_for_url demo&lt;/h1&gt;
    {% if latest_question_list %}
        &lt;ul&gt;
            {% for question in latest_question_list%}
                &lt;li&gt;&lt;a href="{% url 'polls:index_for_url' question.id %}"&gt;{{question.question_text}}&lt;/a&gt;&lt;/li&gt;
            {% endfor %}
        &lt;/ul&gt;
    {% else %}
        &lt;p&gt;No polls are availabel.&lt;/p&gt;
    {% endif %}
&lt;/body&gt;
&lt;/html&gt;
</code></pre><p style="margin: 1em 0px; word-wrap: break-word;"><strong>视图函数</strong></p><pre style="border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); overflow: auto; padding: 0.5em;"><code data-origin="<pre><code>def index_for_url(request):

    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    print latest_question_list
    context = {'latest_question_list': latest_question_list, 'title': 'index_for_url'}    
    return render(request, 'polls/index_for_url.html', context)
</code></pre>" style="border: 0px; display: block;font-family: Consolas, Inconsolata, Courier, monospace; font-weight: bold; white-space: pre; margin: 0px;border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); padding: 0px 5px; margin: 0px 2px;font-size: 1em; letter-spacing: -1px; font-weight: bold;">def index_for_url(request):

    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    print latest_question_list
    context = {'latest_question_list': latest_question_list, 'title': 'index_for_url'}    
    return render(request, 'polls/index_for_url.html', context)
</code></pre><p style="margin: 1em 0px; word-wrap: break-word;"><strong>URL配置</strong></p><pre style="border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); overflow: auto; padding: 0.5em;"><code data-origin="<pre><code>url(r'^index_for_url/$', views.index_for_url, name='index_for_url'),

url(r'^index_for_url/(?P&amp;lt;question_id&amp;gt;[0-9]+)/$', views.detail, name='detail'),
</code></pre>" style="border: 0px; display: block;font-family: Consolas, Inconsolata, Courier, monospace; font-weight: bold; white-space: pre; margin: 0px;border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); padding: 0px 5px; margin: 0px 2px;font-size: 1em; letter-spacing: -1px; font-weight: bold;">url(r'^index_for_url/$', views.index_for_url, name='index_for_url'),

url(r'^index_for_url/(?P&lt;question_id&gt;[0-9]+)/$', views.detail, name='detail'),
</code></pre><p style="margin: 1em 0px; word-wrap: break-word;"><strong>异常</strong></p><pre style="border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); overflow: auto; padding: 0.5em;"><code data-origin="<pre><code>NoReverseMatch at /polls/index_for_url/
Reverse for 'index_for_url' with arguments '(2,)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'polls/index_for_url/$']
</code></pre>" style="border: 0px; display: block;font-family: Consolas, Inconsolata, Courier, monospace; font-weight: bold; white-space: pre; margin: 0px;border-top-left-radius: 3px; border-top-right-radius: 3px; border-bottom-right-radius: 3px; border-bottom-left-radius: 3px; word-wrap: break-word; border: 1px solid rgb(204, 204, 204); padding: 0px 5px; margin: 0px 2px;font-size: 1em; letter-spacing: -1px; font-weight: bold;">NoReverseMatch at /polls/index_for_url/
Reverse for 'index_for_url' with arguments '(2,)' and keyword arguments '{}' not found. 1 pattern(s) tried: [u'polls/index_for_url/$']
</code></pre></div>

**Comment by 7sDream** [comment]
```HTML
{% url 'polls:index_for_url' question.id %}
```

你这里用的名字 index_for_url 在 urls name 的里找不到啊

你应该改成

```HTML
{% url 'polls:detail' question.id %}
```

另外，发代码不要这样发 =。= 看起来有麻烦，用 Markdown 语法就好。
