### ISSUE TITLE
中文版 404

### ISSUE THREAD

**Issue by RRRoger** [7sDream/django-intro-zh#20]
中文版 404

**Comment by 7sDream** [comment]
经验证并没有 404。请确认访问的是这个页面：http://7sdream.github.io/django-intro-zh/

**Comment by RRRoger** [comment]
https://github.com/7sDream/django-intro-zh/blob/master/glance.md

**Comment by RRRoger** [comment]
知道了 必须在http://7sdream.github.io/django-intro-zh/ 这个page里点才有用
